// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5BeCLhTS9uY4qcfiYOXzx3QpC6Aqn56s',
    appId: '1:1067631613889:web:1a5d78f1a3b147342d4140',
    messagingSenderId: '1067631613889',
    projectId: 'phoneauthenticationwithbloc',
    authDomain: 'phoneauthenticationwithbloc.firebaseapp.com',
    storageBucket: 'phoneauthenticationwithbloc.appspot.com',
    measurementId: 'G-762LF84NB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrvBWSHBcIcnmKflxizQXEYS_UHRW_R4',
    appId: '1:1067631613889:android:cf09c8317e28189f2d4140',
    messagingSenderId: '1067631613889',
    projectId: 'phoneauthenticationwithbloc',
    storageBucket: 'phoneauthenticationwithbloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQOZdl9VwQ1O3QwmKtWallM_4IIWRJ_Q',
    appId: '1:1067631613889:ios:886fa915b5be62d62d4140',
    messagingSenderId: '1067631613889',
    projectId: 'phoneauthenticationwithbloc',
    storageBucket: 'phoneauthenticationwithbloc.appspot.com',
    iosClientId: '1067631613889-tkut5m6pr0eb3nh512dca797f9rcgc6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQOZdl9VwQ1O3QwmKtWallM_4IIWRJ_Q',
    appId: '1:1067631613889:ios:c46956f2e2bdfd6c2d4140',
    messagingSenderId: '1067631613889',
    projectId: 'phoneauthenticationwithbloc',
    storageBucket: 'phoneauthenticationwithbloc.appspot.com',
    iosClientId: '1067631613889-4qe7saule7i8lnkfmiefopgq441852ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
